### PR TITLE
Added new Library(Picasso) in the README.md file

### PR DESCRIPTION
**Pull request by IamRaja007**
For issue -->  Add More Libraries to Directory #1

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
Thanks @IamRaja007  for your contribution

**Comment by IamRaja007** [comment]
Welcome!. Hey, can you mark this PR as "hacktoberfest-accepted" ?

**Comment by yogeshpaliyal** [comment]
This repo has topic `hacktoberfest` so there is no need to add hacktoberfest-accepted label

**Comment by IamRaja007** [comment]
Okay! thats good to know. Thanks Yogesh.

**Pull request merged**
